### ISSUE TITLE
Load Images from Drawable folder

### ISSUE THREAD

**Issue by ShagunParikh** [gotokatsuya/KenBurnsView#3]
Please update your project to allow the developers to load image from local resources as well. that is from Drawable folder, asset folder etc.

You are using Glide Library image loader library. They support the local image loading.

Thank you.

**Comment by gotokatsuya** [comment]
@ShagunParikh 

Thank you for your comment. 

It's nice. Please wait to update.

**Comment by gotokatsuya** [comment]
@ShagunParikh 

Please check v1.0.1 !!

Thank you.

**Comment by ShagunParikh** [comment]
Thanks.
